name: 'Beta Release'
on:
  push:
    branches:
    - master
jobs:
  build-test-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.1.1

      - run: dotnet restore               # install packages
      - run: dotnet build -c Release --no-restore    # build
      - run: 'dotnet test -c Release --no-build --verbosity normal --filter TestCategory!=EOR --logger "trx;LogFileName=test-results.trx"' # run tests
      - run: 'cp "${{ github.workspace }}/DatReaderWriter.Tests/TestResults/test-results.trx" "${{ github.workspace }}/test-results.xml" '
      - uses: actions/upload-artifact@v4  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: 'test-results.xml'

      - run: dotnet pack -c Release --no-restore
  
      - uses: actions/upload-artifact@v4  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with: 
          name: packages
          path: "${{ github.workspace }}/DatReaderWriter/bin/Release/DatReaderWriter.${{ env.GitVersion_FullSemVer }}.nupkg"

      - run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ACClientLib/index.json"
 
      - run: dotnet nuget push "${{ github.workspace }}/DatReaderWriter/bin/Release/DatReaderWriter.${{ env.GitVersion_FullSemVer }}.nupkg" --api-key ${{ secrets.CI_NUGET_API_KEY }} --source "github"
